server:
  port: 5001
  servlet:
    context-path: /consulPayment
# 服务别名---注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consul-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 心跳机制没有打开 报红
        heartbeat:
          enabled: true