server:
  port: 3001
# 服务名
spring:
  application:
    name: cloud-nacos-sentinel
# 注册进nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#
management:
  endpoints:
    web:
      exposure:
        include: '*'