server:
  port: 6002
  servlet:
    context-path: /zookeeperOrder
# 服务别名---注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-zookeeper-order
  cloud:
    zookeeper:
      connect-string: 192.168.159.128:2181