server:
  port: 8022
  servlet:
    context-path: /order
# eureka客户端
eureka:
  instance:
    instance-id: order8022
    prefer-ip-address: true #访问路径可以显示IP地址
  client:
    # 表示是否把自己注册进eurekaserver 默认为true
    register-with-eureka: true
    # 是否从eurekaserver抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
# 服务名
spring:
  application:
    name: cloud-feign-hystrix-service

# 设置feign客户端超时时间（openfeign默认支持ribbon）
ribbon:
# 指的是建议连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 6000
# 指的是建立连接后从服务端读取到可用资源所用的时间
  ConnectTimeout: 6000
# 此配置和 OpenFeign 打印日志级别有关
logging:
  level:
    #feign日志以什么级别监控那个接口
    com.taiji.cloudopen.service.UserClientService: debug

feign:
  hystrix:
    enabled: false