server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端得实例名称
  client:
    # false表示不想注册中心注册自己
    registerWithEureka: false
    #false表示自己端就是注册中心，我得职责是维护服务实例，并不需要去检索服务
    fetchRegistry: false
    serviceUrl:
    #设置与eureka server交互的地址查询服务和注册服务都需要
      defaultZone: http://eureka7001.com:7001/eureka/
