server:
  port: 8001
  servlet:
    context-path: /cloud

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloudtest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  devtools:
    restart:
      enabled: false  #设置关闭热部署

mybatis:
  mapperLocations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.taiji.model