server:
  port: 8011
  servlet:
    context-path: /cloud
# eureka客户端
eureka:
  instance:
    instance-id: payment8011
    prefer-ip-address: true #访问路径可以显示IP地址
  client:
    # 表示是否把自己注册进eurekaserver 默认为true
    register-with-eureka: true
    # 是否从eurekaserver抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
# 服务名
spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloudtest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  devtools:
    restart:
      enabled: false  #设置关闭热部署

mybatis:
  mapperLocations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.taiji.model